version: '3'

services:
  php:
    container_name: contact-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./api:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - contact-network

  nginx:
    container_name: contact-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8989:80'
      - '443:443'
    volumes:
      - ./api:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - contact-network
  
  node:
    container_name: contact-node
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports: 
      - '4200:4200'
    volumes: 
      - ./web/:/usr/src/app/web 
    command: > 
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    networks:
      - contact-network

  mysql:
    container_name: contact-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - contact-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - contact-network
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpmyadmin:
    container_name: contact-phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    ports:
      - '8888:80'
    networks:
      - contact-network
    environment:
      PMA_HOST: contact-mysql
    depends_on:
      - mysql

  redis:
    container_name: contact-redis
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - '6379:6379'

networks:
  contact-network:
    driver: bridge


volumes:
  contact-data:
    driver: local